"""Generate small rational-ring certificates for the finite variance proof."""
from pathlib import Path
from ring import atom, theorem, HEADER, ZERO, ONE

x,w,v,u,s,t,a,b=map(atom,('x','w','v','u','s','t','a','b'))
def center(x,u,s,t): return t-((ONE+ONE)*x)*s+(x*x)*u
specs=[
    ('center_empty',['x'],ZERO,center(x,ZERO,ZERO,ZERO)),
    ('center_step',['x','w','v','u','s','t'],w*((v-x)*(v-x))+center(x,u,s,t),center(x,w+u,w*v+s,w*(v*v)+t)),
    ('lagrange_step',['w','x','u','s','t'],(w+u)*(w*(x*x)+t)-(w*x+s)*(w*x+s),(u*t-s*s)+w*center(x,u,s,t)),
    ('add_sub_cancel',['a','b'],a+(b-a),b),
]
out=Path(__file__).resolve().parents[1]/'Exact'/'MomentAlgebra.bend'
content='# Generated by tools/build_moment_proofs.py; checked by Bend.\n'+HEADER+''.join(theorem(*spec) for spec in specs)
out.write_text(content)
print(f'{out.name}: {len(content.splitlines())} lines, {len(content)} bytes')
