"""Generate congruence and transitivity certificates, with explicit hypotheses."""
from pathlib import Path
import semiring as S
from semiring import atom, proof, DagRenderer
from build_rational_proofs import variable, certificate

OUT = Path(__file__).resolve().parents[1] / 'Exact'
header = '# Generated by tools/build_equality_proofs.py; checked by Bend.\nimport Base\nimport ./Natural.bend as N\nimport ./Cancellation.bend as C\n'
algebra = [header]

def poly(name, names, l, r):
    renderer = DagRenderer()
    S.RENDERER = renderer
    try:
        body = proof(l, r)
    finally:
        S.RENDERER = None
    decl = '\nlaw '+name+':\n'+''.join(f'  for +{n}: N.Number\n' for n in names)
    decl += f'  {{{l.raw()} == {r.raw()} : N.Number}}\ndef {name}('+', '.join(names)+'):\n'
    algebra.append(decl + ''.join(renderer.lines).replace('      +','  +') + body)

names = ['ap','an','ad','bp','bn','bd','cp','cn','cd']
ap,an,ad,bp,bn,bd,cp,cn,cd = map(atom,names)
l, r = ap*bd+bn*ad, bp*ad+an*bd
kl,kr = cp*cd,cn*cd
common=(cp+cn)*ad*bd*cd
addl=(ap*cd+cp*ad)*(bd*cd)+(bn*cd+cn*bd)*(ad*cd)
addr=(bp*cd+cp*bd)*(ad*cd)+(an*cd+cn*ad)*(bd*cd)
poly('add_left',names,addl,common+(cd*cd)*l)
poly('add_right',names,addr,common+(cd*cd)*r)
mull=(ap*cp+an*cn)*(bd*cd)+(bp*cn+bn*cp)*(ad*cd)
mulr=(bp*cp+bn*cn)*(ad*cd)+(ap*cn+an*cp)*(bd*cd)
poly('mul_left',names,mull,kl*l+kr*r)
poly('mul_right',names,mulr,kl*r+kr*l)
common2=bp*ad*cd+bn*ad*cd
sl=bd*(ap*cd+cn*ad)
sr=bd*(cp*ad+an*cd)
l2,r2=bp*cd+cn*bd,cp*bd+bn*cd
poly('trans_left',names,common2+sl,ad*l2+cd*l)
poly('trans_right',names,common2+sr,ad*r2+cd*r)
args=', '.join(names)
params=''.join(f'  for +{n}: N.Number\n' for n in names)

def eq(a,b):
    return '{'+a.raw()+' == '+b.raw()+' : N.Number}'

def trans(a,b,c,ab,bc):
    return f'Equal.trans(N.Number, {a.raw()}, {b.raw()}, {c.raw()}, {ab}, {bc})'

def sym(a,b,e):
    return f'Equal.sym(N.Number, {a.raw()}, {b.raw()}, {e})'

middle=common+(cd*cd)*l
end=common+(cd*cd)*r
body=trans(addl,middle,addr,f'add_left({args})',trans(middle,end,addr,f'Equal.cong(N.Number, N.Number, x => N.add({common.raw()}, N.mul({(cd*cd).raw()}, x)), {l.raw()}, {r.raw()}, e)',sym(addr,end,f'add_right({args})')))
algebra.append(f'\nlaw add_compat:\n{params}  for e: {eq(l,r)}\n  {eq(addl,addr)}\ndef add_compat({args}, e):\n  {body}\n')

algebra.append('''
law swap_equal:
  for +l: N.Number
  for +r: N.Number
  for +p: N.Number
  for +n: N.Number
  for e: {l == r : N.Number}
  {N.add(N.mul(p, l), N.mul(n, r)) == N.add(N.mul(p, r), N.mul(n, l)) : N.Number}
def swap_equal(l, r, p, n, e):
  %e : {N.add(N.mul(p, l), N.mul(n, _)) == N.add(N.mul(p, _), N.mul(n, l)) : N.Number}
  {==}
''')
ml,mr=kl*l+kr*r,kl*r+kr*l
body=trans(mull,ml,mulr,f'mul_left({args})',trans(ml,mr,mulr,f'swap_equal({l.raw()}, {r.raw()}, {kl.raw()}, {kr.raw()}, e)',sym(mulr,mr,f'mul_right({args})')))
algebra.append(f'\nlaw mul_compat:\n{params}  for e: {eq(l,r)}\n  {eq(mull,mulr)}\ndef mul_compat({args}, e):\n  {body}\n')

algebra.append('''
law add_equal:
  for +l: N.Number
  for +r: N.Number
  for +u: N.Number
  for +v: N.Number
  for +p: N.Number
  for +q: N.Number
  for e: {l == r : N.Number}
  for f: {u == v : N.Number}
  {N.add(N.mul(p, u), N.mul(q, l)) == N.add(N.mul(p, v), N.mul(q, r)) : N.Number}
def add_equal(l, r, u, v, p, q, e, f):
  %e : {N.add(N.mul(p, u), N.mul(q, l)) == N.add(N.mul(p, v), N.mul(q, _)) : N.Number}
  %f : {N.add(N.mul(p, u), N.mul(q, l)) == N.add(N.mul(p, _), N.mul(q, l)) : N.Number}
  {==}
''')
tl,tr=ad*l2+cd*l,ad*r2+cd*r
middleproof=f'add_equal({l.raw()}, {r.raw()}, {l2.raw()}, {r2.raw()}, {ad.raw()}, {cd.raw()}, e, f)'
body=trans(common2+sl,tl,common2+sr,f'trans_left({args})',trans(tl,tr,common2+sr,middleproof,sym(common2+sr,tr,f'trans_right({args})')))
algebra.append(f'\nlaw trans_scaled:\n{params}  for e: {eq(l,r)}\n  for f: {eq(l2,r2)}\n  {eq(sl,sr)}\ndef trans_scaled({args}, e, f):\n  C.add_cancel({common2.raw()}, {sl.raw()}, {sr.raw()}, {body})\n')
(OUT/'EqualityAlgebra.bend').write_text(''.join(algebra))

q=['# Generated by tools/build_equality_proofs.py; checked by Bend.\nimport Base\nimport ./Natural.bend as N\nimport ./Binary.bend as B\nimport ./BinaryProof.bend as BP\nimport ./Rational.bend as Q\nimport ./Cancellation.bend as C\nimport ./EqualityAlgebra.bend as A\n']
a,b,c=map(variable,('a','b','c'))
field_args=', '.join(f'B.{"positive_value" if n.endswith("d") else "value"}({n})' for n in names)
for name,op in [('add_congr',lambda a,c:a+c),('mul_congr',lambda a,c:a*c)]:
    left,right=op(a,c),op(b,c)
    q.append(f'\nlaw {name}:\n  for +a: Q.Number\n  for +b: Q.Number\n  for +c: Q.Number\n  for e: Q.Eq(a, b)\n  Q.Eq({left.text}, {right.text})\ndef {name}(a, b, c, e):\n  match a b c e:\n    case Q.Fraction{{ap, an, ad}} Q.Fraction{{bp, bn, bd}} Q.Fraction{{cp, cn, cd}} Q.Witness{{e}}:\n')
    renderer=DagRenderer()
    S.RENDERER=renderer
    try:
        body=certificate(left,right,finish=lambda l,r: f'      A.{name.split("_")[0]}_compat({field_args}, e)\n')
    finally:
        S.RENDERER=None
    q.extend(renderer.lines)
    q.append(body)

q.append('''
law sym:
  for +a: Q.Number
  for +b: Q.Number
  for e: Q.Eq(a, b)
  Q.Eq(b, a)
def sym(a, b, e):
  match a b e:
    case Q.Fraction{ap, an, ad} Q.Fraction{bp, bn, bd} Q.Witness{e}:
      Q.Witness{Equal.sym(N.Number,
        N.add(N.mul(B.value(ap), B.positive_value(bd)), N.mul(B.value(bn), B.positive_value(ad))),
        N.add(N.mul(B.value(bp), B.positive_value(ad)), N.mul(B.value(an), B.positive_value(bd))), e)}

law cancel_positive:
  for +k: B.Positive
  for +b: N.Number
  for +c: N.Number
  {N.mul(B.positive_value(k), b) == N.mul(B.positive_value(k), c) : N.Number} -> {b == c : N.Number}
def cancel_positive(k, b, c):
  %Equal.sym(N.Number, B.positive_value(k), N.S{C.positive_tail(k)}, C.positive(k)) : {N.mul(_, b) == N.mul(_, c) : N.Number} -> {b == c : N.Number}
  e => C.mul_cancel(b, c, C.positive_tail(k), e)

law trans:
  for +a: Q.Number
  for +b: Q.Number
  for +c: Q.Number
  for e: Q.Eq(a, b)
  for f: Q.Eq(b, c)
  Q.Eq(a, c)
def trans(a, b, c, e, f):
  match a b c e f:
    case Q.Fraction{ap, an, ad} Q.Fraction{bp, bn, bd} Q.Fraction{cp, cn, cd} Q.Witness{e} Q.Witness{f}:
      Q.Witness{cancel_positive(bd,
        N.add(N.mul(B.value(ap), B.positive_value(cd)), N.mul(B.value(cn), B.positive_value(ad))),
        N.add(N.mul(B.value(cp), B.positive_value(ad)), N.mul(B.value(an), B.positive_value(cd))))(
''')
q.append(f'        A.trans_scaled({field_args}, e, f))}}\n')
(OUT/'RationalEquality.bend').write_text(''.join(q))
print('Generated rational congruence and transitivity certificates.')
