"""Certify the embedding of executable nonnegative rational arithmetic."""
from pathlib import Path
import semiring as S
from semiring import DagRenderer
from build_rational_proofs import Binary, Rational, BZ, certificate

out=['# Generated by tools/build_order_proofs.py; checked by Bend.\nimport Base\nimport ./Natural.bend as N\nimport ./Binary.bend as B\nimport ./BinaryProof.bend as BP\nimport ./Rational.bend as Q\n']
a=Rational('Q.of_nonnegative(a)',Binary('an'),BZ,Binary('ad',True))
b=Rational('Q.of_nonnegative(b)',Binary('bn'),BZ,Binary('bd',True))
for name,op in [('add',lambda a,b:a+b),('mul',lambda a,b:a*b)]:
    l=op(a,b)
    p=(a.p*b.d+b.p*a.d) if name=='add' else a.p*b.p
    r=Rational(f'Q.of_nonnegative(Q.nonnegative_{name}(a, b))',p,BZ,a.d*b.d)
    out.append(f'\nlaw {name}_embedding:\n  for +a: Q.Nonnegative\n  for +b: Q.Nonnegative\n  Q.Eq({l.text}, {r.text})\ndef {name}_embedding(a, b):\n  match a b:\n    case Q.Nonnegative{{an, ad}} Q.Nonnegative{{bn, bd}}:\n')
    renderer=DagRenderer()
    S.RENDERER=renderer
    try:
        body=certificate(l,r)
    finally:
        S.RENDERER=None
    out.extend(renderer.lines)
    out.append(body)
path=Path(__file__).resolve().parents[1]/'Exact'/'OrderAlgebra.bend'
path.write_text(''.join(out))
print('Generated nonnegative embedding certificates.')
