"""Generate exact cancellation identities for strictly positive divisors."""
from pathlib import Path
import semiring as S
from semiring import DagRenderer
from build_rational_proofs import variable, Binary, Rational, BZ, certificate

q=variable('a')
u=Rational('Q.of_positive(u)',Binary('un',True).whole(),BZ,Binary('ud',True))
def divide(a):
    return Rational(f'Q.div_positive({a.text}, u)',a.p*u.d,a.n*u.d,a.d*Binary('un',True))
def divide_square(a):
    root=Binary('un',True)*Binary('un',True)
    return Rational(f'Q.div_positive({a.text}, Q.positive_mul(u, u))',a.p*(Binary('ud',True)*Binary('ud',True)),a.n*(Binary('ud',True)*Binary('ud',True)),a.d*root)
specs=[('divide_cancel',u*divide(q),q),('square_divide',u*(divide(q)*divide(q)),divide(q*q)),
       ('root_square_divide',divide_square(q*q),divide(q)*divide(q))]
out=['# Generated by tools/build_division_proofs.py; checked by Bend.\nimport Base\nimport ./Natural.bend as N\nimport ./Binary.bend as B\nimport ./BinaryProof.bend as BP\nimport ./Rational.bend as Q\n']
for name,l,r in specs:
    out.append(f'\nlaw {name}:\n  for +a: Q.Number\n  for +u: Q.Positive\n  Q.Eq({l.text}, {r.text})\ndef {name}(a, u):\n  match a u:\n    case Q.Fraction{{ap, an, ad}} Q.Positive{{un, ud}}:\n')
    renderer=DagRenderer();S.RENDERER=renderer
    try: body=certificate(l,r)
    finally: S.RENDERER=None
    out.extend(renderer.lines);out.append(body)
path=Path(__file__).resolve().parents[1]/'Exact'/'DivisionAlgebra.bend'
path.write_text(''.join(out))
print('Generated positive-division certificates.')
