"""Regenerate binary-arithmetic certificates; run from any directory."""
from pathlib import Path
from semiring import Z, ONE, atom, proof

OUT = Path(__file__).resolve().parents[1] / 'Exact' / 'BinaryProof.bend'
lines = ['# Generated by tools/build_binary_proofs.py; checked by Bend.\nimport Base\nimport ./Natural.bend as N\nimport ./Binary.bend as B\n']

def replace(e, old, new):
    if e == old:
        return new
    if e.op in ('add', 'mul'):
        return type(e)(e.op, tuple(replace(x, old, new) for x in e.args))
    return e

def branch(pattern, left, right, rewrites=()):
    lines.append(f'    case {pattern}:\n')
    for old, new, evidence in rewrites:
        context = replace(left, old, atom('_'))
        lines.append(f'      %Equal.sym(N.Number, {old.render()}, {new.render()}, {evidence}) : {{{context.render()} == {right.render()} : N.Number}}\n')
        left = replace(left, old, new)
    lines.append(proof(left, right, '      '))

def law(name, params, goal, match):
    lines.append(f'\nlaw {name}:\n')
    for name_, type_ in params:
        lines.append(f'  for +{name_}: {type_}\n')
    lines.append(f'  {goal}\ndef {name}(' + ', '.join(p[0] for p in params) + f'):\n  match {match}:\n')

x = atom('B.positive_value(p)')
y = atom('B.positive_value(q)')
b = atom('B.positive_value(b)')
incp = atom('B.positive_value(B.inc(p))')
incb = atom('B.positive_value(B.inc(b))')
addpq = atom('B.positive_value(B.positive_add(p, q))')

law('inc_correct', [('a', 'B.Positive')], '{B.positive_value(B.inc(a)) == N.S{B.positive_value(a)} : N.Number}', 'a')
branch('B.One{}', ONE + ONE, ONE + ONE)
branch('B.Bit0{p}', ONE + (x + x), ONE + (x + x))
branch('B.Bit1{p}', incp + incp, ONE + (ONE + (x + x)), [(incp, ONE + x, 'inc_correct(p)')])

law('positive_add_correct', [('a', 'B.Positive'), ('b', 'B.Positive')], '{B.positive_value(B.positive_add(a, b)) == N.add(B.positive_value(a), B.positive_value(b)) : N.Number}', 'a b')
branch('B.One{} b', incb, ONE + b, [(incb, ONE + b, 'inc_correct(b)')])
branch('B.Bit0{p} B.One{}', ONE + (x + x), (x + x) + ONE)
branch('B.Bit1{p} B.One{}', incp + incp, (ONE + (x + x)) + ONE, [(incp, ONE + x, 'inc_correct(p)')])
for abit in (0, 1):
    for bbit in (0, 1):
        l = addpq + addpq
        rewrites = []
        if abit + bbit == 1:
            l = ONE + l
        if abit + bbit == 2:
            i = atom('B.positive_value(B.inc(B.positive_add(p, q)))')
            l = i + i
            rewrites.append((i, ONE + addpq, 'inc_correct(B.positive_add(p, q))'))
        rewrites.append((addpq, x + y, 'positive_add_correct(p, q)'))
        a = x + x if abit == 0 else ONE + (x + x)
        b_ = y + y if bbit == 0 else ONE + (y + y)
        branch(f'B.Bit{abit}{{p}} B.Bit{bbit}{{q}}', l, a + b_, rewrites)

law('positive_mul_correct', [('a', 'B.Positive'), ('b', 'B.Positive')], '{B.positive_value(B.positive_mul(a, b)) == N.mul(B.positive_value(a), B.positive_value(b)) : N.Number}', 'a')
branch('B.One{}', b, ONE * b)
m = atom('B.positive_value(B.positive_mul(p, b))')
branch('B.Bit0{p}', m + m, (x + x) * b, [(m, x * b, 'positive_mul_correct(p, b)')])
s = atom('B.positive_value(B.positive_add(b, B.Bit0{B.positive_mul(p, b)}))')
branch('B.Bit1{p}', s, (ONE + (x + x)) * b, [(s, b + (m + m), 'positive_add_correct(b, B.Bit0{B.positive_mul(p, b)})'), (m, x * b, 'positive_mul_correct(p, b)')])

law('add_correct', [('a', 'B.Whole'), ('b', 'B.Whole')], '{B.value(B.add(a, b)) == N.add(B.value(a), B.value(b)) : N.Number}', 'a b')
branch('B.Zero{} b', atom('B.value(b)'), Z + atom('B.value(b)'))
branch('B.Pos{p} B.Zero{}', x, x + Z)
branch('B.Pos{p} B.Pos{q}', addpq, x + y, [(addpq, x + y, 'positive_add_correct(p, q)')])

law('mul_correct', [('a', 'B.Whole'), ('b', 'B.Whole')], '{B.value(B.mul(a, b)) == N.mul(B.value(a), B.value(b)) : N.Number}', 'a b')
branch('B.Zero{} b', Z, Z * atom('B.value(b)'))
branch('B.Pos{p} B.Zero{}', Z, x * Z)
m = atom('B.positive_value(B.positive_mul(p, q))')
branch('B.Pos{p} B.Pos{q}', m, x * y, [(m, x * y, 'positive_mul_correct(p, q)')])

OUT.write_text(''.join(lines))
print(f'{OUT.name}: {len("".join(lines).splitlines())} lines')
