#!/usr/bin/env python3
"""Install the repository's plain-Markdown prompts into native CLI surfaces.

Markdown-capable hosts receive relative symlinks to the canonical files. Gemini
CLI receives generated TOML because its custom-command format is different.
Existing user files are never overwritten; a conflict is reported instead.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
PROMPTS = BASE / "prompts"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
GENERATED_PREFIX = "# Generated by scripts/install-prompts.py from prompts/"


def _home_value(home: Path, variable: str, default: Path, use_environment: bool) -> Path:
    if use_environment and os.environ.get(variable):
        return Path(os.environ[variable]).expanduser()
    return home / default


def host_targets(home: Path, use_environment: bool) -> list[tuple[str, str, Path, str]]:
    """Return (host, executable, target directory, file extension) entries."""
    pi_root = _home_value(home, "PI_CODING_AGENT_DIR", Path(".pi/agent"), use_environment)
    claude_root = _home_value(home, "CLAUDE_CONFIG_DIR", Path(".claude"), use_environment)
    codex_root = _home_value(home, "CODEX_HOME", Path(".codex"), use_environment)
    xdg_config = _home_value(home, "XDG_CONFIG_HOME", Path(".config"), use_environment)
    opencode_root = _home_value(
        home,
        "OPENCODE_CONFIG_DIR",
        xdg_config / "opencode",
        use_environment,
    )
    gemini_root = _home_value(home, "GEMINI_CLI_HOME", Path(".gemini"), use_environment)
    return [
        ("pi", "pi", pi_root / "prompts", ".md"),
        ("claude", "claude", claude_root / "commands", ".md"),
        ("codex", "codex", codex_root / "prompts", ".md"),
        ("opencode", "opencode", opencode_root / "commands", ".md"),
        ("cursor", "cursor-agent", home / ".cursor" / "commands", ".md"),
        ("agy", "agy", gemini_root / "config" / "global_workflows", ".md"),
        ("gemini", "gemini", gemini_root / "commands", ".toml"),
    ]


def prompt_files() -> list[Path]:
    return sorted(PROMPTS.glob("*.md"))


def validate_prompts() -> list[str]:
    errors: list[str] = []
    if not PROMPTS.is_dir():
        return ["prompts/: directory is missing"]
    files = prompt_files()
    if not files:
        return ["prompts/: no top-level Markdown prompts found"]
    for path in files:
        if not NAME_RE.fullmatch(path.stem):
            errors.append(f"invalid prompt name: prompts/{path.name}")
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read prompts/{path.name}: {exc}")
            continue
        if not text.strip():
            errors.append(f"empty prompt: prompts/{path.name}")
        if "$ARGUMENTS" not in text:
            errors.append(f"prompts/{path.name}: missing shared $ARGUMENTS placeholder")
        if text.lstrip().startswith("---"):
            errors.append(
                f"prompts/{path.name}: keep canonical prompts plain Markdown; host metadata is derived"
            )
        if "{{args}}" in text:
            errors.append(
                f"prompts/{path.name}: use $ARGUMENTS; {{{{args}}}} is Gemini-specific"
            )
    return errors


def _enabled(executable: str, force_all: bool) -> bool:
    return force_all or shutil.which(executable) is not None


def _exists(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def _ensure_directory(path: Path, mutate: bool, errors: list[str]) -> bool:
    if _exists(path) and not path.is_dir():
        errors.append(f"host target is not a directory: {path}")
        return False
    if not path.is_dir():
        if not mutate:
            errors.append(f"missing host directory: {path}")
            return False
        try:
            path.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            errors.append(f"cannot create host directory {path}: {exc}")
            return False
    return True


def _link(source: Path, target: Path, mutate: bool, errors: list[str]) -> str:
    source_resolved = source.resolve()
    if target.is_symlink():
        try:
            if target.resolve(strict=False) == source_resolved:
                return "ok"
        except OSError:
            pass
        errors.append(f"conflicting symlink (left unchanged): {target}")
        return "conflict"
    if target.exists():
        errors.append(f"conflicting file (left unchanged): {target}")
        return "conflict"
    if not mutate:
        errors.append(f"missing prompt link: {target}")
        return "missing"
    try:
        relative = os.path.relpath(source_resolved, target.parent.resolve())
        target.symlink_to(relative)
    except OSError as exc:
        errors.append(f"cannot link {target}: {exc}")
        return "error"
    return "created"


def _description(text: str, fallback: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line:
            if line.startswith("#"):
                line = line.lstrip("#").strip()
            return line or fallback
    return fallback


def _toml_string(value: str) -> str:
    # JSON string escaping is the same escaping subset accepted by TOML basic strings.
    return json.dumps(value, ensure_ascii=False)


def _gemini_adapter(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    body = text.replace("$ARGUMENTS", "{{args}}")
    description = _description(text, source.stem.replace("-", " "))
    return (
        f"{GENERATED_PREFIX}{source.name}.\n"
        f"description = {_toml_string(description)}\n"
        f"prompt = {_toml_string(body)}\n"
    )


def _write_adapter(source: Path, target: Path, mutate: bool, errors: list[str]) -> str:
    expected = _gemini_adapter(source)
    was_existing = target.exists()
    if target.is_symlink():
        errors.append(f"conflicting symlink (left unchanged): {target}")
        return "conflict"
    if target.exists():
        try:
            current = target.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read existing adapter {target}: {exc}")
            return "error"
        if not current.startswith(GENERATED_PREFIX):
            errors.append(f"conflicting file (left unchanged): {target}")
            return "conflict"
        if current == expected:
            return "ok"
        if not mutate:
            errors.append(f"stale generated adapter: {target}")
            return "stale"
    elif not mutate:
        errors.append(f"missing Gemini adapter: {target}")
        return "missing"
    try:
        target.write_text(expected, encoding="utf-8")
    except OSError as exc:
        errors.append(f"cannot write Gemini adapter {target}: {exc}")
        return "error"
    return "updated" if was_existing else "created"


def sync(home: Path, mutate: bool, force_all: bool, use_environment: bool) -> tuple[int, list[str]]:
    errors: list[str] = []
    actions = 0
    files = prompt_files()
    targets = host_targets(home, use_environment)
    for host, executable, directory, extension in targets:
        if not _enabled(executable, force_all):
            continue
        if not _ensure_directory(directory, mutate, errors):
            continue
        for source in files:
            target = directory / f"{source.stem}{extension}"
            if extension == ".toml":
                result = _write_adapter(source, target, mutate, errors)
            else:
                result = _link(source, target, mutate, errors)
            if result in {"created", "updated"}:
                actions += 1
    return actions, errors


def _selftest() -> int:
    errors = validate_prompts()
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory(prefix="prompt-mounts-") as temp:
        home = Path(temp)
        actions, install_errors = sync(home, True, True, False)
        if install_errors:
            for error in install_errors:
                print(error, file=sys.stderr)
            return 1
        _, check_errors = sync(home, False, True, False)
        if check_errors:
            for error in check_errors:
                print(error, file=sys.stderr)
            return 1
        for source in prompt_files():
            for _, _, directory, extension in host_targets(home, False):
                target = directory / f"{source.stem}{extension}"
                if extension == ".md" and not target.is_symlink():
                    print(f"selftest: missing symlink {target}", file=sys.stderr)
                    return 1
                if extension == ".toml":
                    try:
                        import tomllib

                        data = tomllib.loads(target.read_text(encoding="utf-8"))
                    except Exception as exc:  # noqa: BLE001
                        print(f"selftest: invalid TOML {target}: {exc}", file=sys.stderr)
                        return 1
                    expected = source.read_text(encoding="utf-8").replace(
                        "$ARGUMENTS", "{{args}}"
                    )
                    if data.get("prompt") != expected:
                        print(f"selftest: adapter drift {target}", file=sys.stderr)
                        return 1
        conflict_target = home / ".claude" / "commands" / "repo-audit.md"
        conflict_target.unlink()
        conflict_target.write_text("user-owned\\n", encoding="utf-8")
        _, conflict_errors = sync(home, True, True, False)
        if not any(
            "conflicting file (left unchanged)" in error
            and str(conflict_target) in error
            for error in conflict_errors
        ):
            print("selftest: unmanaged-file conflict was not rejected", file=sys.stderr)
            return 1
        if conflict_target.read_text(encoding="utf-8") != "user-owned\\n":
            print("selftest: unmanaged-file conflict was overwritten", file=sys.stderr)
            return 1
        print(f"PROMPT INSTALLER SELFTEST PASS ({actions} generated entries)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check installed host mounts without changing them")
    parser.add_argument("--check-repo", action="store_true", help="validate canonical prompts only")
    parser.add_argument("--selftest", action="store_true", help="run the isolated installer self-test")
    parser.add_argument("--all", action="store_true", help="include known hosts even when their executable is not on PATH")
    parser.add_argument("--home", type=Path, help="alternate home root for testing or isolated installation")
    args = parser.parse_args()

    if args.selftest:
        return _selftest()
    repo_errors = validate_prompts()
    if args.check_repo:
        if repo_errors:
            for error in repo_errors:
                print(error, file=sys.stderr)
            return 1
        print(f"PROMPT SURFACE OK ({len(prompt_files())} prompts)")
        return 0
    if repo_errors:
        for error in repo_errors:
            print(error, file=sys.stderr)
        return 1

    use_environment = args.home is None
    home = (args.home or Path.home()).expanduser().resolve()
    actions, errors = sync(home, not args.check, args.all, use_environment)
    if errors:
        print("PROMPT MOUNT CHECK FAILED:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    mode = "CHECK" if args.check else "INSTALLED"
    print(f"PROMPT MOUNTS {mode} ({actions} changes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
