#!/usr/bin/env python3
"""Install the repository's plain-Markdown prompts into native CLI surfaces.

Markdown-capable hosts receive relative symlinks to the canonical files. Gemini
CLI receives generated TOML because its custom-command format is different.
Existing unmanaged files are never overwritten or removed; a conflict is reported instead.
Obsolete installer-managed entries are removed only when they are provable. This helper does
not install skills; eager-host skill exposure uses README.md's filtered symlink route.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
PROMPTS = BASE / "prompts"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
GENERATED_PREFIX = "# Generated by scripts/install-prompts.py from prompts/"


def _home_value(home: Path, variable: str, default: Path, use_environment: bool) -> Path:
    if use_environment and os.environ.get(variable):
        return Path(os.environ[variable]).expanduser()
    return home / default


def host_targets(home: Path, use_environment: bool) -> list[tuple[str, str, Path, str]]:
    """Return (host, executable, target directory, file extension) entries."""
    pi_root = _home_value(home, "PI_CODING_AGENT_DIR", Path(".pi/agent"), use_environment)
    claude_root = _home_value(home, "CLAUDE_CONFIG_DIR", Path(".claude"), use_environment)
    codex_root = _home_value(home, "CODEX_HOME", Path(".codex"), use_environment)
    xdg_config = _home_value(home, "XDG_CONFIG_HOME", Path(".config"), use_environment)
    opencode_root = _home_value(
        home,
        "OPENCODE_CONFIG_DIR",
        xdg_config / "opencode",
        use_environment,
    )
    gemini_root = _home_value(home, "GEMINI_CLI_HOME", Path(".gemini"), use_environment)
    return [
        ("pi", "pi", pi_root / "prompts", ".md"),
        ("claude", "claude", claude_root / "commands", ".md"),
        ("codex", "codex", codex_root / "prompts", ".md"),
        ("opencode", "opencode", opencode_root / "commands", ".md"),
        ("cursor", "cursor-agent", home / ".cursor" / "commands", ".md"),
        ("agy", "agy", gemini_root / "config" / "global_workflows", ".md"),
        ("gemini", "gemini", gemini_root / "commands", ".toml"),
    ]


def prompt_files() -> list[Path]:
    return sorted(PROMPTS.glob("*.md"))


def validate_prompts() -> list[str]:
    errors: list[str] = []
    if not PROMPTS.is_dir():
        return ["prompts/: directory is missing"]
    files = prompt_files()
    if not files:
        return ["prompts/: no top-level Markdown prompts found"]
    for path in files:
        if not NAME_RE.fullmatch(path.stem):
            errors.append(f"invalid prompt name: prompts/{path.name}")
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read prompts/{path.name}: {exc}")
            continue
        if not text.strip():
            errors.append(f"empty prompt: prompts/{path.name}")
        if "$ARGUMENTS" not in text:
            errors.append(f"prompts/{path.name}: missing shared $ARGUMENTS placeholder")
        if text.lstrip().startswith("---"):
            errors.append(
                f"prompts/{path.name}: keep canonical prompts plain Markdown; host metadata is derived"
            )
        if "{{args}}" in text:
            errors.append(
                f"prompts/{path.name}: use $ARGUMENTS; {{{{args}}}} is Gemini-specific"
            )
    return errors


def _enabled(executable: str, force_all: bool) -> bool:
    return force_all or shutil.which(executable) is not None


def _exists(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def _ensure_directory(path: Path, mutate: bool, errors: list[str]) -> bool:
    if _exists(path) and not path.is_dir():
        errors.append(f"host target is not a directory: {path}")
        return False
    if not path.is_dir():
        if not mutate:
            errors.append(f"missing host directory: {path}")
            return False
        try:
            path.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            errors.append(f"cannot create host directory {path}: {exc}")
            return False
    return True


def _link(source: Path, target: Path, mutate: bool, errors: list[str]) -> str:
    source_resolved = source.resolve()
    if target.is_symlink():
        try:
            if target.resolve(strict=False) == source_resolved:
                return "ok"
        except OSError:
            pass
        errors.append(f"conflicting symlink (left unchanged): {target}")
        return "conflict"
    if target.exists():
        errors.append(f"conflicting file (left unchanged): {target}")
        return "conflict"
    if not mutate:
        errors.append(f"missing prompt link: {target}")
        return "missing"
    try:
        relative = os.path.relpath(source_resolved, target.parent.resolve())
        target.symlink_to(relative)
    except OSError as exc:
        errors.append(f"cannot link {target}: {exc}")
        return "error"
    return "created"


def _generated_source_name(path: Path) -> str | None:
    """Return the canonical source named by a generated Gemini adapter."""
    if path.is_symlink() or not path.is_file():
        return None
    try:
        with path.open(encoding="utf-8") as stream:
            line = stream.readline().rstrip("\n")
    except OSError:
        return None
    if not line.startswith(GENERATED_PREFIX) or not line.endswith("."):
        return None
    source_name = line[len(GENERATED_PREFIX) : -1]
    source = Path(source_name)
    if (
        source.name != source_name
        or source.suffix != ".md"
        or not NAME_RE.fullmatch(source.stem)
    ):
        return None
    return source_name


def _managed_markdown_target(target: Path) -> bool:
    if not target.is_symlink():
        return False
    try:
        source = target.resolve(strict=False)
    except OSError:
        return False
    return (
        source.parent == PROMPTS.resolve()
        and source.name == target.name
        and NAME_RE.fullmatch(source.stem) is not None
    )


def _obsolete_targets(
    directory: Path, extension: str, expected_names: set[str]
) -> list[Path]:
    if not directory.is_dir():
        return []
    candidates = directory.glob(f"*{extension}")
    if extension == ".md":
        return sorted(
            path
            for path in candidates
            if path.name not in expected_names and _managed_markdown_target(path)
        )

    obsolete: list[Path] = []
    for path in candidates:
        source_name = _generated_source_name(path)
        if (
            source_name is not None
            and path.name == Path(source_name).with_suffix(".toml").name
            and path.name not in expected_names
        ):
            obsolete.append(path)
    return sorted(obsolete)


def _remove_obsolete(
    directory: Path,
    extension: str,
    expected_names: set[str],
    mutate: bool,
    errors: list[str],
) -> int:
    actions = 0
    for target in _obsolete_targets(directory, extension, expected_names):
        if not mutate:
            errors.append(f"obsolete managed prompt: {target}")
            continue
        try:
            target.unlink()
        except OSError as exc:
            errors.append(f"cannot remove obsolete prompt {target}: {exc}")
        else:
            actions += 1
    return actions


def _description(text: str, fallback: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line:
            if line.startswith("#"):
                line = line.lstrip("#").strip()
            return line or fallback
    return fallback


def _toml_string(value: str) -> str:
    # JSON string escaping is the same escaping subset accepted by TOML basic strings.
    return json.dumps(value, ensure_ascii=False)


def _parse_generated_toml(text: str) -> dict[str, str]:
    """Parse the exact two-string TOML shape emitted by this script."""
    lines = text.splitlines()
    if not lines or not lines[0].startswith(GENERATED_PREFIX):
        raise ValueError("missing generated adapter marker")
    values: dict[str, str] = {}
    for line in lines[1:]:
        if not line.strip():
            continue
        key, separator, encoded = line.partition(" = ")
        if separator != " = " or key not in {"description", "prompt"}:
            raise ValueError(f"unexpected generated adapter line: {line!r}")
        if key in values:
            raise ValueError(f"duplicate generated adapter key: {key}")
        value = json.loads(encoded)
        if not isinstance(value, str):
            raise ValueError(f"generated adapter key is not a string: {key}")
        values[key] = value
    if set(values) != {"description", "prompt"}:
        raise ValueError("generated adapter is missing a required string")
    return values


def _parse_adapter(text: str) -> dict[str, str]:
    try:
        import tomllib
    except ModuleNotFoundError:
        return _parse_generated_toml(text)
    return tomllib.loads(text)


def _gemini_adapter(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    body = text.replace("$ARGUMENTS", "{{args}}")
    description = _description(text, source.stem.replace("-", " "))
    return (
        f"{GENERATED_PREFIX}{source.name}.\n"
        f"description = {_toml_string(description)}\n"
        f"prompt = {_toml_string(body)}\n"
    )


def _atomic_write_text(target: Path, text: str, replace=os.replace) -> None:
    """Write a complete adapter then atomically replace its destination."""
    fd, raw = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    temp = Path(raw)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        replace(temp, target)
    finally:
        temp.unlink(missing_ok=True)


def _write_adapter(source: Path, target: Path, mutate: bool, errors: list[str]) -> str:
    expected = _gemini_adapter(source)
    was_existing = target.exists()
    if target.is_symlink():
        errors.append(f"conflicting symlink (left unchanged): {target}")
        return "conflict"
    if target.exists():
        try:
            current = target.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read existing adapter {target}: {exc}")
            return "error"
        if not current.startswith(GENERATED_PREFIX):
            errors.append(f"conflicting file (left unchanged): {target}")
            return "conflict"
        if current == expected:
            return "ok"
        if not mutate:
            errors.append(f"stale generated adapter: {target}")
            return "stale"
    elif not mutate:
        errors.append(f"missing Gemini adapter: {target}")
        return "missing"
    try:
        _atomic_write_text(target, expected)
    except OSError as exc:
        errors.append(f"cannot write Gemini adapter {target}: {exc}")
        return "error"
    return "updated" if was_existing else "created"


def sync(home: Path, mutate: bool, force_all: bool, use_environment: bool) -> tuple[int, list[str]]:
    errors: list[str] = []
    actions = 0
    files = prompt_files()
    targets = host_targets(home, use_environment)
    for _, executable, directory, extension in targets:
        if not _enabled(executable, force_all):
            continue
        if not _ensure_directory(directory, mutate, errors):
            continue
        expected_names = {f"{source.stem}{extension}" for source in files}
        for source in files:
            target = directory / f"{source.stem}{extension}"
            if extension == ".toml":
                result = _write_adapter(source, target, mutate, errors)
            else:
                result = _link(source, target, mutate, errors)
            if result in {"created", "updated"}:
                actions += 1
        actions += _remove_obsolete(
            directory, extension, expected_names, mutate, errors
        )
    return actions, errors


def _selftest() -> int:
    errors = validate_prompts()
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory(prefix="prompt-mounts-") as temp:
        home = Path(temp)
        actions, install_errors = sync(home, True, True, False)
        if install_errors:
            for error in install_errors:
                print(error, file=sys.stderr)
            return 1
        _, check_errors = sync(home, False, True, False)
        if check_errors:
            for error in check_errors:
                print(error, file=sys.stderr)
            return 1
        for source in prompt_files():
            for _, _, directory, extension in host_targets(home, False):
                target = directory / f"{source.stem}{extension}"
                if extension == ".md" and not target.is_symlink():
                    print(f"selftest: missing symlink {target}", file=sys.stderr)
                    return 1
                if extension == ".toml":
                    try:
                        data = _parse_adapter(target.read_text(encoding="utf-8"))
                    except Exception as exc:  # noqa: BLE001
                        print(f"selftest: invalid TOML {target}: {exc}", file=sys.stderr)
                        return 1
                    expected = source.read_text(encoding="utf-8").replace(
                        "$ARGUMENTS", "{{args}}"
                    )
                    if data.get("prompt") != expected:
                        print(f"selftest: adapter drift {target}", file=sys.stderr)
                        return 1
        sample_source = prompt_files()[0]
        fallback_data = _parse_generated_toml(_gemini_adapter(sample_source))
        fallback_expected = sample_source.read_text(encoding="utf-8").replace(
            "$ARGUMENTS", "{{args}}"
        )
        if fallback_data.get("prompt") != fallback_expected:
            print("selftest: Python 3.10 TOML fallback drift", file=sys.stderr)
            return 1
        stale_markdown = home / ".claude" / "commands" / "renamed-away.md"
        stale_markdown.symlink_to(
            os.path.relpath(PROMPTS / stale_markdown.name, stale_markdown.parent.resolve())
        )
        stale_gemini = home / ".gemini" / "commands" / "renamed-away.toml"
        stale_gemini.write_text(
            f"{GENERATED_PREFIX}{stale_markdown.name}.\n"
            'description = "old"\n'
            'prompt = "old"\n',
            encoding="utf-8",
        )
        unmanaged_gemini = home / ".gemini" / "commands" / "user-owned.toml"
        unmanaged_gemini.write_text('prompt = "user-owned"\n', encoding="utf-8")
        _, stale_check_errors = sync(home, False, True, False)
        for target in (stale_markdown, stale_gemini):
            if not any(
                "obsolete managed prompt" in error and str(target) in error
                for error in stale_check_errors
            ):
                print(f"selftest: stale mount was not reported: {target}", file=sys.stderr)
                return 1
        _, stale_remove_errors = sync(home, True, True, False)
        if (
            stale_remove_errors
            or _exists(stale_markdown)
            or _exists(stale_gemini)
            or unmanaged_gemini.read_text(encoding="utf-8") != 'prompt = "user-owned"\n'
        ):
            print("selftest: stale managed mount was not removed safely", file=sys.stderr)
            return 1
        conflict_target = home / ".claude" / "commands" / "repo-audit.md"
        conflict_target.unlink()
        conflict_target.write_text("user-owned\n", encoding="utf-8")
        _, conflict_errors = sync(home, True, True, False)
        if not any(
            "conflicting file (left unchanged)" in error
            and str(conflict_target) in error
            for error in conflict_errors
        ):
            print("selftest: unmanaged-file conflict was not rejected", file=sys.stderr)
            return 1
        if conflict_target.read_text(encoding="utf-8") != "user-owned\n":
            print("selftest: unmanaged-file conflict was overwritten", file=sys.stderr)
            return 1
        atomic_target = home / "atomic.txt"
        atomic_target.write_text("old\n", encoding="utf-8")

        def fail_replace(_source, _target):
            raise OSError("injected replace failure")
        try:
            _atomic_write_text(atomic_target, "new\n", replace=fail_replace)
        except OSError:
            pass
        if atomic_target.read_text(encoding="utf-8") != "old\n":
            print("selftest: failed atomic write changed destination", file=sys.stderr)
            return 1
        if list(home.glob(".atomic.txt.*")):
            print("selftest: failed atomic write left a temporary file", file=sys.stderr)
            return 1
        print(f"PROMPT INSTALLER SELFTEST PASS ({actions} generated entries; atomic adapters)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check installed host mounts without changing them")
    parser.add_argument("--check-repo", action="store_true", help="validate canonical prompts only")
    parser.add_argument("--selftest", action="store_true", help="run the isolated installer self-test")
    parser.add_argument("--all", action="store_true", help="include known hosts even when their executable is not on PATH")
    parser.add_argument("--home", type=Path, help="alternate home root for testing or isolated installation")
    args = parser.parse_args()

    if args.selftest:
        return _selftest()
    repo_errors = validate_prompts()
    if args.check_repo:
        if repo_errors:
            for error in repo_errors:
                print(error, file=sys.stderr)
            return 1
        print(f"PROMPT SURFACE OK ({len(prompt_files())} prompts)")
        return 0
    if repo_errors:
        for error in repo_errors:
            print(error, file=sys.stderr)
        return 1

    use_environment = args.home is None
    home = (args.home or Path.home()).expanduser().resolve()
    actions, errors = sync(home, not args.check, args.all, use_environment)
    if errors:
        print("PROMPT MOUNT CHECK FAILED:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    mode = "CHECK" if args.check else "INSTALLED"
    print(f"PROMPT MOUNTS {mode} ({actions} changes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
